#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v3
# autospec commit: c1050fe
#
# Source0 file verified with key 0x51722B08FE4745A2 (simon@josefsson.org)
#
Name     : inetutils
Version  : 2.5
Release  : 8
URL      : https://mirrors.kernel.org/gnu/inetutils/inetutils-2.5.tar.xz
Source0  : https://mirrors.kernel.org/gnu/inetutils/inetutils-2.5.tar.xz
Source1  : https://mirrors.kernel.org/gnu/inetutils/inetutils-2.5.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: inetutils-bin = %{version}-%{release}
Requires: inetutils-info = %{version}-%{release}
Requires: inetutils-license = %{version}-%{release}
Requires: inetutils-man = %{version}-%{release}
BuildRequires : Linux-PAM-dev
BuildRequires : bison
BuildRequires : buildreq-configure
BuildRequires : glibc-locale
BuildRequires : ncurses-dev
BuildRequires : readline-dev
BuildRequires : sed
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
GNU inetutils - The GNU Networking Utilities
The GNU Networking Utilities are the common networking utilities,
clients and servers of the GNU Operating System developed by the GNU
project.

%package bin
Summary: bin components for the inetutils package.
Group: Binaries
Requires: inetutils-license = %{version}-%{release}

%description bin
bin components for the inetutils package.


%package info
Summary: info components for the inetutils package.
Group: Default

%description info
info components for the inetutils package.


%package license
Summary: license components for the inetutils package.
Group: Default

%description license
license components for the inetutils package.


%package man
Summary: man components for the inetutils package.
Group: Default

%description man
man components for the inetutils package.


%prep
%setup -q -n inetutils-2.5
cd %{_builddir}/inetutils-2.5
pushd ..
cp -a inetutils-2.5 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1704225150
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%configure --disable-static --disable-dnsdomainname \
--disable-ftp \
--disable-ftpd \
--disable-inetd \
--disable-hostname \
--disable-ifconfig \
--disable-logger \
--disable-ping \
--disable-ping6 \
--disable-rcp \
--disable-rexec \
--disable-rexecd \
--disable-rlogin \
--disable-rlogind \
--disable-rsh \
--disable-rshd \
--disable-syslogd \
--disable-talk \
--disable-talkd \
--disable-telnetd \
--disable-tftp \
--disable-tftpd \
--disable-traceroute \
--disable-uucpd \
--disable-whois \
--enable-telnet
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -m64 -march=x86-64-v3 "
LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
%configure --disable-static --disable-dnsdomainname \
--disable-ftp \
--disable-ftpd \
--disable-inetd \
--disable-hostname \
--disable-ifconfig \
--disable-logger \
--disable-ping \
--disable-ping6 \
--disable-rcp \
--disable-rexec \
--disable-rexecd \
--disable-rlogin \
--disable-rlogind \
--disable-rsh \
--disable-rshd \
--disable-syslogd \
--disable-talk \
--disable-talkd \
--disable-telnetd \
--disable-tftp \
--disable-tftpd \
--disable-traceroute \
--disable-uucpd \
--disable-whois \
--enable-telnet
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1704225150
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/inetutils
cp %{_builddir}/inetutils-%{version}/COPYING %{buildroot}/usr/share/package-licenses/inetutils/aeb23ef9343dcd5bfaf91ec1088f508e646f5370 || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/telnet
/usr/bin/telnet

%files info
%defattr(0644,root,root,0755)
/usr/share/info/inetutils.info

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/inetutils/aeb23ef9343dcd5bfaf91ec1088f508e646f5370

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/telnet.1
